# Generated by Django 4.0.2 on 2023-09-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_archivo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.CharField(max_length=255),
        ),
    ]
